/** App-facing domain types.
 *
 * These are now DERIVED from the backend OpenAPI schema via
 * `src/lib/api.types.ts` (generated by `npm run codegen`). Re-exporting under
 * the same names keeps call sites unchanged while guaranteeing the shapes
 * never drift from the backend contract. Run codegen after backend changes;
 * CI fails on drift.
 *
 * Only the convenience aliases below are hand-written. */

import type { components } from "./api.types";

type Schemas = components["schemas"];

// Convenience aliases (not represented as named OpenAPI schemas).
export type UUID = string;
export type ISODateTime = string;

// === Auth ===
export type UserPublic = Schemas["UserPublic"];
export type TokenPair = Schemas["TokenPair"];
export type LoginResponse = Schemas["LoginResponse"];

// === Domain ===
export type StorePublic = Schemas["StorePublic"];
export type CameraPublic = Schemas["CameraPublic"];
export type ClipPublic = Schemas["ClipPublic"];

export type AlertCategory = Schemas["AlertCategory"];
export type AlertLevel = Schemas["AlertLevel"];
export type AlertPublic = Schemas["AlertPublic"];

export type FeedbackVerdict = Schemas["FeedbackVerdict"];
export type FeedbackPublic = Schemas["FeedbackPublic"];

// === Org / admin ===
export type OrgRole = Schemas["OrgRole"];
export type OrganizationPublic = Schemas["OrganizationPublic"];

// === Agents (camera-relay PC pairing) ===
export type PairingCodePublic = Schemas["PairingCodePublic"];
export type AgentPublic = Schemas["AgentPublic"];

// === Behaviors ===
export type BehaviorDimension = Schemas["BehaviorDimension"];
export type BehaviorConfig = Schemas["BehaviorConfig"];
export type BehaviorConfigPatch = Schemas["BehaviorConfigPatch"];
