/** App-facing domain types.
 *
 * These are now DERIVED from the backend OpenAPI schema via
 * `src/lib/api.types.ts` (generated by `npm run codegen`). Re-exporting under
 * the same names keeps call sites unchanged while guaranteeing the shapes
 * never drift from the backend contract. Run codegen after backend changes;
 * CI fails on drift.
 *
 * Only the convenience aliases below are hand-written. */

import type { components } from "./api.types";

type Schemas = components["schemas"];

// Convenience aliases (not represented as named OpenAPI schemas).
export type UUID = string;
export type ISODateTime = string;

// === Auth ===
export type UserPublic = Schemas["UserPublic"];
// Tokens live only in httpOnly cookies (ADR-0017) — no TokenPair in the API body.
export type LoginResponse = Schemas["LoginResponse"];

// === Domain ===
export type StorePublic = Schemas["StorePublic"];
export type CameraPublic = Schemas["CameraPublic"];
export type ClipPublic = Schemas["ClipPublic"];
/** A per-camera detection zone (docs/29) — normalized 0-1 polygon. */
export type Zone = Schemas["Zone"];

export type AlertCategory = Schemas["AlertCategory"];
export type AlertLevel = Schemas["AlertLevel"];
export type AlertPublic = Schemas["AlertPublic"];

export type FeedbackVerdict = Schemas["FeedbackVerdict"];
export type FeedbackPublic = Schemas["FeedbackPublic"];

// === Event / activity log ===
export type EventLogPublic = Schemas["EventLogPublic"];
export type EventType = Schemas["EventType"];
export type EventSeverity = Schemas["EventSeverity"];

// === Org / admin ===
export type OrgRole = Schemas["OrgRole"];
export type OrganizationPublic = Schemas["OrganizationPublic"];

// === Agents (camera-relay PC pairing) ===
export type PairingCodePublic = Schemas["PairingCodePublic"];
export type AgentPublic = Schemas["AgentPublic"];

// === Floor plan + analytics (docs/30) ===
// All derived from the backend OpenAPI schema (regenerated via `npm run
// codegen`). The list-valued fields (walls/fixtures/cells/edges/…) come through
// as optional because the backend defaults them via `default_factory`; the
// analytics endpoints always return them, so `Required<…>` here restores the
// non-optional shape the /insights components rely on.
export type FloorFixture = Schemas["FloorFixture"];
export type FloorFixtureType = FloorFixture["type"];
export type FloorWall = Schemas["FloorWall"];
export type FloorCamera = Schemas["FloorCamera"];
export type FloorPlan = Required<Schemas["FloorPlan"]>;

export type FootfallGrid = Required<Schemas["FootfallGrid"]>;
export type TrafficPoint = Schemas["TrafficPoint"];
export type TrafficSummary = Required<Schemas["TrafficSummary"]>;
export type ZoneActivity = Schemas["ZoneActivity"];
export type ZoneBreakdown = Required<Schemas["ZoneBreakdown"]>;
export type FlowEdge = Schemas["FlowEdge"];
export type FlowSummary = Required<Schemas["FlowSummary"]>;
export type PeakCell = Schemas["PeakCell"];
export type PeakMatrix = Required<Schemas["PeakMatrix"]>;

// === Behaviors ===
export type BehaviorDimension = Schemas["BehaviorDimension"];
export type BehaviorConfig = Schemas["BehaviorConfig"];
export type BehaviorConfigPatch = Schemas["BehaviorConfigPatch"];
